### ISSUE TITLE
selectionを独自のものを入れる

### ISSUE THREAD

**Issue by kentoishizuka** [hisamikurita/hisamikurita-portfoliosite#2]
::selection {
    background: #000;
    color: #f2f2f2;
    text-shadow: 0.05em 0.05em 0 rgb(255 0 0), 0.05em -0.05em 0 rgb(0 255 0), -0.05em 0.05em 0 rgb(0 0 255);

を追加してほしい

元ネタ
https://andmade.jp/about

**Comment by hisamikurita** [comment]
面白いですねコレ。

**Comment by hisamikurita** [comment]
text-shadow入れると、テキスト選択したままスクロールするとぐう重くなります。。

**Comment by hisamikurita** [comment]
@kentoishizuka 
こんなんでどうです？？
https://agitated-mayer-c19e77.netlify.app/
